
language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
   - wget -c https://files.seeedstudio.com/arduino/seeed-arduino-ci.sh

script:
   - chmod +x seeed-arduino-ci.sh
   - cat $PWD/seeed-arduino-ci.sh
   - bash $PWD/seeed-arduino-ci.sh analog_output:uno/button:uno/echo_ble:uno/get_bat_vol:uno/rgb_led_matrix_control:uno/serial_transparent_transmission:uno/temp_humidity:uno

notifications:
  email:
    on_success: change
    on_failure: change
